Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false